### ISSUE TITLE
Stuck here, I can do anything

### ISSUE THREAD

**Issue by fadyOne** [BuidlGuidl/flashbot-recovery-bundler#4]
<img width="1440" alt="Screenshot 2023-11-13 at 22 35 51" src="https://github.com/BuidlGuidl/flashbot-recovery-bundler/assets/10937545/95f7df9c-79ec-4980-acc5-31922d5f86bf">
first steps where ok, connect wallet 1, connect wallet to sponsor fees then nothing even refresh

**Comment by escottalexander** [comment]
We have deployed a lot of changes to the build since you left this feedback. We believe your issue may be resolved. Let us know if that is not the case and we will reopen this issue.

**Comment by escottalexander** [comment]
You did well to add your asset manually. Sorry that you ran into that bug. We will look into it and get back to you.

**Comment by escottalexander** [comment]
The solution to the bug is being reviewed and will hopefully be merged in within a few days. You can track progress here: https://github.com/BuidlGuidl/flashbot-recovery-bundler/pull/17

**Comment by escottalexander** [comment]
We just deployed a couple fixes that I believe will help your issue. Still sorting out some weirdness but I think you should be able to recover your assets. Report back if you have any more issues.

**Comment by escottalexander** [comment]
I am curious to see more about that 405 error you got. If you can duplicate the scenario open up your network tab in the chrome dev tools and post all the info for that failing request.

You should not lose any ETH when it fails as long as each wallet is connected to the special RPC. Are both your hacked wallet and funding wallet (safe wallet) connected to the Hacked Wallet Recovery RPC?

Don't worry about the pending transactions. The RPC is different in that all your transactions are pending until they are all completed. Did you clear all the Metamask tab data between recoveries? If you still have pending transactions after it fails then you will not succeed a second time.

Lastly, use the gas suggestion that the site gives you. If you change it yourself or even allow Metamask to suggest a different option, it is likely to fail. Feel free to hit me up on Telegram if you want hep walking through things. My TG handle is the same as my github handle.

**Comment by escottalexander** [comment]
Any updates on this issue? If not I will close next time I sort through them.
